export const statesAndCities = [
  { state: 'New York', city: 'New York' },
  { state: 'Phoenix', city: 'Arizona' },
  { state: 'Atlanta', city: 'Georgia' },
  { state: 'Chicago', city: 'Illinois' },
  { state: 'Miami', city: 'Florida' },
  { state: 'San Diego', city: 'California' },
  { state: 'San Francisco', city: 'California' },
  { state: 'Nashville', city: 'Tennessee' },
  { state: 'Seattle', city: 'Washington' },
  { state: 'Boston', city: 'Massachusetts' },
  { state: 'Philadelphia', city: 'Pennsylvania' },
  { state: 'Dallas', city: 'Texas' },
  { state: 'Austin', city: 'Texas' },
  { state: 'Washington', city: 'District of Columbia' },
  { state: 'New Orleans', city: 'Louisiana' },
  { state: 'San Antonio', city: 'Texas' },
  { state: 'Houston', city: 'Texas' },
  { state: 'Los Angeles', city: 'California' },
  { state: 'London', city: 'United Kingdom' },
  { state: 'Paris', city: 'France' },
  { state: 'Memphis', city: 'Tennessee' },
  { state: 'Rome', city: 'Italy' },
  { state: 'Barcelona', city: 'Spain' },
  { state: 'Amsterdam', city: 'Netherlands' },
  { state: 'Lexington', city: 'Kentucky' }
]
